# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Tests Devops

on:
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
      issues: write
      pull-requests: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 2
    - run: |
        gh pr comment "$PR_NUMBER" --repo "$GITHUB_REPOSITORY" --body "job started"
      env:
        GH_TOKEN: ${{ github.token }}
        PR_NUMBER: ${{ github.event.number }}
