# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Tests Devops

on:
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
    - run: |
        gh pr comment "$PR_NUMBER" --repo "$GITHUB_REPOSITORY" --body "job started"
