# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Tests Devops

on:
  pull_request: {}
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
    - run: |
        echo "${{ toJson(github.event.head_commit.message) }}"
