# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Tests Devops

on:
  pull_request: {}
  push:
    branches:
    - main
    - '!migration-**'

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
    - run: echo "test"
